

export interface Book {
    id: string;
    title: string;
    description: string;
    imageUrl: string;
    rating?: number; // User's personal rating
    
    // For community rating on core books
    communityRating?: number;
    ratingCount?: number;
    
    // For pre-loaded books from the /public folder
    contentPath?: string;

    // For user-added books stored in IndexedDB
    file?: File;
    isUserAdded?: boolean;

    // URL for reading/viewing. For pre-loaded, it's same as contentPath. For user-added, it's a generated blob URL.
    downloadUrl?: string; 
    
    // Specific URL for the download button, overrides downloadUrl for that action.
    downloadActionUrl?: string;

    // Explicit filename for content fetched from a URL, helps identify filetype if MIME is generic.
    fileName?: string;

    // Smart categories generated by AI
    categories?: string[];
    isLoading?: boolean;
}

export interface Video {
    id: string;
    title: string;
    description: string;
    thumbnailUrl: string;
    rating?: number;
    communityRating?: number;
    ratingCount?: number;
    contentPath?: string;
    file?: File;
    isUserAdded?: boolean;
    downloadUrl?: string;
    downloadActionUrl?: string;
    fileName?: string;
    script?: string;
    isLoading?: boolean;
}

export interface Audio {
    id: string;
    title: string;
    description: string;
    thumbnailUrl: string;
    rating?: number;
    communityRating?: number;
    ratingCount?: number;
    contentPath?: string;
    file?: File;
    isUserAdded?: boolean;
    downloadUrl?: string;
    downloadActionUrl?: string;
    fileName?: string;
    isLoading?: boolean;
}

export interface Image {
    id: string;
    title: string;
    description: string;
    url: string;
    rating?: number;
    communityRating?: number;
    ratingCount?: number;
    contentPath?: string;
    file?: File;
    isUserAdded?: boolean;
    downloadUrl?: string;
    downloadActionUrl?: string;
    fileName?: string;
    isLoading?: boolean;
}


export interface QuizQuestion {
    question: string;
    options: string[];
    correctAnswerIndex: number;
}

export interface QuizResult {
    score: number;
    total: number;
}

export interface SentimentResult {
    sentiment: 'إيجابي' | 'سلبي' | 'محايد';
    explanation: string;
}

export interface Note {
  id: string;
  content: string;
  createdAt: number; // Storing timestamp for easier sorting
}